### ISSUE TITLE
Nightly dev builds failing

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#163]
From 04/07/23, the nightly dev builds in github actions began failing in the "Decrpyt a secret" step with the following error:
```bash
gpg: gcry_kdf_derive failed: Invalid data
gpg: decryption failed: No secret key
Error: Process completed with exit code 2.
```

For example: https://github.com/DiamondLightSource/httomo/actions/runs/5686700912/job/15413946524

**Comment by dkazanc** [comment]
thanks, I'm wondering why this work for httomolib(gpu), as we use exactly the same decryption system there?

**Comment by yousefmoazzam** [comment]
I'm not sure since I'm not familiar with how the decryption stuff actually works.

In the action output, the script being run `.scripts/decrypt_secret.sh` can be expanded to see some info about the environment it was executed in. The httomo expanded output for that failing job shows
```bash
Run ./.scripts/decrypt_secret.sh
  ./.scripts/decrypt_secret.sh
  shell: /usr/bin/bash -l {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
    LARGE_SECRET_PASSPHRASE: 
```

whereas httomolibgpu in https://github.com/DiamondLightSource/httomolibgpu/actions/runs/5756949779/job/15607252188 shows
```bash
Run ./.scripts/decrypt_secret.sh
  ./.scripts/decrypt_secret.sh
  shell: /usr/bin/bash -l {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
    LARGE_SECRET_PASSPHRASE: ***
```

The entry for `LARGE_SECRET_PASSPHRASE` is empty for httomo, and is non-empty for httomolibgpu. This would suggest that the environment variable `LARGE_SECRET_PASSPHRASE` is empty for httomo when that script executes in the action, but is non-empty for httomolibgpu.

This would make sense as far as the error is concerned, since I'm guessing the phrase "No secret key" is referring to the fact that `LARGE_SECRET_PASSPHRASE` is empty?

But this is where my knowledge ends unfortunately, I don't know how `LARGE_SECRET_PASSPHRASE` should be getting defined, so I can't tell what the difference is between httomo and httomolib(gpu).

**Comment by dkazanc** [comment]
thanks. yes, looks like  LARGE_SECRET_PASSPHRASE is not set for httomo as I probably forgot. Let me have a look into this, we might need to create new...

**Comment by yousefmoazzam** [comment]
It's progress https://github.com/DiamondLightSource/httomo/actions/runs/5767622636/job/15637592583, `LARGE_SECRET_PASSPHRASE` appears to now be defined, but another error has replaced it :sweat_smile::
```sh
Run ./.scripts/decrypt_secret.sh
  ./.scripts/decrypt_secret.sh
  shell: /usr/bin/bash -l {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
    LARGE_SECRET_PASSPHRASE: ***
gpg: decryption failed: Bad session key
```

**Comment by dkazanc** [comment]
yes, I think we need to redefine a new secret. Will do that...

**Comment by dkazanc** [comment]
I pushed the new secret and the passphrase. Let see what happens this night

**Comment by dkazanc** [comment]
OK, it worked but the package name was set incorrectly. I changed it to httomo, should upload correctly this time.

**Comment by yousefmoazzam** [comment]
Cool, thanks for sorting that out! :slightly_smiling_face:

**Comment by dkazanc** [comment]
Ok, now it is finally [sorted](https://anaconda.org/httomo/httomo). Channel had to be specified directly.
