### ISSUE TITLE
add GPU devices indices into logs

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#172]
Currently [this](https://github.com/DiamondLightSource/httomo/blob/1f8714955845dcadfd58d1a7ee07e31766984d16/httomo/wrappers_class.py#L48C17-L48C17) logging command won't be executed for all ranks but rank 0. Since `httomo.globals.logger.debug` is None for non-zero ranks.  We need to ensure that we log all the ranks, and therefore GPU devices associated. 
If it is not possible within one log file, may be for the parallel run we could create a folder with logs for each process?

**Comment by yousefmoazzam** [comment]
Completed in merge of #294
