### ISSUE TITLE
binary/3D tiff file saving

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#180]
As requested, investigate the option of saving the resulting file as binary files or stacked 3D tiff

https://stackoverflow.com/questions/18367007/python-how-to-write-to-a-binary-file

**Comment by team-gpu** [comment]
Aren't itermediate files already saved as HDF5, which is a binary format? The advantage of these is that they can be written in parallel using MPI. The options I see here:

1. Stick to HDF5, possibly revising the storage format depending on the user needs (best for parallelism)
2. Use stacked TIFFs with a 2-stage process - each process writes its own part and something joins the files after (could be a sequential overhead, unless it's somehow done in a background separate process without holding back the pipeline, or perhaps in an offline post-processing step)
3. Use something along the lines of the linked StackOverflow - binary dump of data. This will likely need a similar 2-step process as mentioned for 3D TIFFs. 

What do you / users prefer?

**Comment by dkazanc** [comment]
Thanks for the comment and discussion. 
Conclusions: Better to stick to hdf5 as the binary file saving in parallel will be essentially trying to do what parallel hdf5 does anyway. 3D tiff is possible or binary file creation after the parallel job is completed, as in post processing stage and outside of the main task runner. Therefore I'll close this as not planned for now.
