### ISSUE TITLE
Is `DatareducerWrapper` intended to reduce darks and flats one at a time?

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#268]
The current docstring: https://github.com/DiamondLightSource/httomo/blob/0bff94bf70a75c9fadbfd14cae24e62a6c66d9fd/httomo/method_wrappers/datareducer.py#L9-L12

and implementation: https://github.com/DiamondLightSource/httomo/blob/0bff94bf70a75c9fadbfd14cae24e62a6c66d9fd/httomo/method_wrappers/datareducer.py#L42-L50

suggests the title question is answered "yes"?

If so, I'm not sure if it's doing that, it looks like it may suffer a similar problem to the `DezingingWrapper` in #245? (In this case, keeping darks in GPU memory while flats are being transferred and processed on GPU).

**Comment by yousefmoazzam** [comment]
Perhaps the data reducer is only implemented as a CPU method so far, which wouldn't make this as much of an issue?

**Comment by dkazanc** [comment]
the current [implementation](https://github.com/DiamondLightSource/httomo/pull/198/commits/b4cb013c55ed0e4d062fb3468af0d2ad2a88a70a) will be pre-processing flats and darks on the CPU before providing the reduced arrays further to dezinger and normaliser.
