### ISSUE TITLE
Remove old and unused `.readthedocs.yaml` file

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#276]
Unless we find that this file has some use for hosting docs on github pages (the current docs hosting in use for httomo), this can be removed.

**Comment by yousefmoazzam** [comment]
Is this actually completed? The branch that is the most up to date is probably either `gpuloop` or `docs_update`, and both still have this file:
- gpuloop: https://github.com/DiamondLightSource/httomo/blob/gpuloop/.readthedocs.yaml
- `docs_update`: https://github.com/DiamondLightSource/httomo/blob/docs_update/.readthedocs.yaml

**Comment by dkazanc** [comment]
sorry, now it is done with 0b053a6c
