### ISSUE TITLE
Remove unused `angles` and `angles_radians` test fixtures

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#319]
These two fixtures are transferring the angles array to GPU: https://github.com/DiamondLightSource/httomo/blob/833936aaa1049feac5c55a2195e99454dee85fcc/tests/conftest.py#L138-L143

and https://github.com/DiamondLightSource/httomo/blob/833936aaa1049feac5c55a2195e99454dee85fcc/tests/conftest.py#L151-L154

The angles array never needs to be in GPU memory in httomo, and the removal of these fixtures has no effect on tests passing (ie, their removal produces no failing tests), so I think they can safely be removed?

**Comment by dkazanc** [comment]
can be removed, yes
