### ISSUE TITLE
Publish docs only when `main` is updated?

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#328]
Currently, we are both building docs _and_ publishing built docs every time a PR is updated, as well as when `main` gets updated: https://github.com/DiamondLightSource/httomo/blob/826865ed6797d2b42aa1bda92987f68f283b9702/.github/workflows/doc_conda.yml#L3-L10

It feels necessary to attempt to _build_ docs on every update to a PR, to make sure docs building isn't broken by changes. However, it feels a bit unnecessary to _publish_ the built docs for every update in the PR?

It looks like others at DLS are publishing docs only when:
- `main` is updated
- a release tag is found in the latest commit that was pushed that triggered the CI

See the copier template project for example (which is the new-ish standard project skeleton in SSCC for python-based projects): https://github.com/DiamondLightSource/python-copier-template/blob/a243c890ed6b1f10d095d2d7a09234fd426ae94b/.github/workflows/_docs.yml#L46-L54 

Thoughts?

**Comment by dkazanc** [comment]
thanks and good point. We should update only when things get merged to `main` when the tag is pushed.  There is no need to build them for every update in PR. Please go ahead and implement the same strategy in Actions as in the link above. thx
