### ISSUE TITLE
Dynamically calculate chunk size when reslicing, based on `preview`

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#43]
First note that in the following code in the reslicing process, the chunk size in the chunking dimension is hardcoded to be `4`: https://github.com/DiamondLightSource/httomo/blob/ff04bcb067cc430ee9224451e768476c5758f93c/src/httomo/data/hdf/_utils/reslice.py#L42-L49

During investigation of #42, it was discovered that when the previewing being applied is such that one of the dimensions of the cropped data is _smaller_ than `slice_no_in_chunks=4`, an error occurs when attempting to re-chunk the data since the attempted chunk size exceeds a dimension in the given data:
```python
ValueError: Chunk shape must not be greater than data shape in any dimension. (901, 4, 2560) is not compatible with (1801, 3, 2560)
```

The chunk size should therefore be calculated based on the `preview` value to ensure such errors don't occur.

Further along the line, the chunk size may also have more complex calculation logic in order to _optimise_ performance for the physical hardware that the software is being run on, in terms of reading/writing chunked hdf5 data.

**Comment by dkazanc** [comment]
thanks a lot for the investigation! Does it mean that `slices_no_in_chunks = 1` could be a safe default option ? Agree, we should certainly explore how the size of the chunk affects the performance on the larger datasets.

**Comment by yousefmoazzam** [comment]
Yeah that's a good point, if `slices_no_in_chunks = 1` then that would guarantee that the chunk size is valid regardless of the value of `preview` (assuming the other dimensions in which chunking isn't being done are valid), so that would indeed be a safe default value.

**Comment by dkazanc** [comment]
OK, let's stick to one for now and later when things are running smoothly we do the benchmarking?  I think we also need to accept that 3 would be our smallest preview data slab as we can get some problems with one slice in reconstruction and re-slicing potentially. So we might need to check if the user wants one slice and pad it. If this is the case then we could go with the minimum`slices_no_in_chunks = 3` probably?
