### ISSUE TITLE
Broken pipeline tests on `main` due to removal of `auto` param in `remove_outlier` from httomolibgpu

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#431]
This PR in httomolibgpu https://github.com/DiamondLightSource/httomolibgpu/pull/150 which removed `cucim` changed the `remove_outlier` method in httomolibgpu to not need an `axis` parameter anymore. (This is because the `cucim` method was working on 2D data, but the removal of `cucim` caused the `remove_outlier` and `median_filter` methods to work on 3D data once more - working on 3D data means that there's no axis to iterate over 2D images now).

However, some pipeline files still specify the `axis` parameter for the `remove_outlier` method from httomolibgpu, which causes an error: https://github.com/DiamondLightSource/httomo/blob/bb953914ccd4ead6d52b26b5e8796a099ab78703/tests/samples/pipeline_template_examples/pipeline_gpu1.yaml#L24-L29

Also, the dezinging wrapper assumes that an `axis` parameter is needed, and if it's omitted from the pipeline then the wrapper will automatically insert a default value for an `axis` parameter, which now breaks anytime the `remove_outlier` or `median_filter` methods from httomolibgpu are used (because they no longer have an `axis` parameter): https://github.com/DiamondLightSource/httomo/blob/bb953914ccd4ead6d52b26b5e8796a099ab78703/httomo/method_wrappers/dezinging.py#L51-L55

**Comment by dkazanc** [comment]
thanks @yousefmoazzam, I was trying to fix some of it [here](https://github.com/DiamondLightSource/httomo/pull/425/files) actually, including the `self._config_params["axis"]` thing. I'll try to merge that PR after I redirect the docs references to `httomo-backends`. The only thing which fails for me there is the Paganin memory hook... expectantly.
