### ISSUE TITLE
Publishing httomo package to httomolib PyPI URL?

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#466]
I don't know anything about how the PyPI github action works, this is just something that caught my eye when looking over the failed PyPI deployments that are linked in the homepage of the repo.

Should this URL in the PyPI github action config be mentioning `httomolib`, or should it be a different URL for httomo? https://github.com/DiamondLightSource/httomo/blob/01a5f3073a85145193145d03b93c531f1f3d7834/.github/workflows/httomo_pypi_publish.yml#L13

**Comment by dkazanc** [comment]
thanks for spotting this, fill fix it
