### ISSUE TITLE
Migrate from `sphinx-panels` to `sphinx-design`

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#470]
Something I saw when trying to understand why the local docs build has so many warnings (see #468) was that the `sphinx-panels` package was planned to be deprecated in favour of `sphinx-design`, see https://github.com/executablebooks/sphinx-panels/issues/67#issue-955244791.

Luckily, `sphinx-design` has a section in its docs for migrating from `sphinx-panels` to `sphinx-design` https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html#migrating-from-sphinx-panels, so hopefully this wouldn't be too bad to do, and would free us from a deprecated dependency for the docs.

**Comment by dkazanc** [comment]
thanks for spotting this... looks like something we better do for all  httomo packages then.
