### ISSUE TITLE
Write documentation (for developers and users) on features available so far in HTTomo

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#83]
Features to document:
- Datasets
  - Single input and output dataset: `data_in` and `data_out`
  - Running the same method on multiple different inputs: `data_in_multi` (or whatever its renamed-replacement is in #80)
  - Using a method which has one input dataset but mutliple output datasets (such as `find_center_360`): `data_in` and `data_out`
- Parameter sweeps (#62)
  - A note to users on middle slices being saved as tiffs when doing a parameter sweep
- Using/writing Jupyter notebooks that use HTTomo/HTTomolib
- How the `preview` parameter is defined in YAML?
- How to write YAML pipeline files?
- A note to users on the warning message about multiple reslices? (Perhaps with the acceleration of the reslice operation in #82, this message is no longer necessary?)

**Comment by yousefmoazzam** [comment]
Feel free to add and/or amend, everyone!

**Comment by dkazanc** [comment]
I think we need to add a detailed description of the loaders and their parameters [here ](https://diamondlightsource.github.io/httomo/reference/loaders.html#)
This is pretty important to have sooner...

**Comment by yousefmoazzam** [comment]
Outdated, and probably replaced by combination of #282, #287, and #280, so I'll close this.
